-- 직급 테이블
CREATE TABLE mushroom.org_pos (
  POS_NO INT NOT NULL AUTO_INCREMENT,
  POS_NM VARCHAR(50) NOT NULL,
  POS_DESC VARCHAR(200) DEFAULT NULL,
  CREATE_DT DATETIME NOT NULL,
  CREATE_ID VARCHAR(45) NOT NULL,
  UPDATE_DT DATETIME NOT NULL,
  UPDATE_ID VARCHAR(45) NOT NULL,
  PRIMARY KEY (POS_NO),
  UNIQUE KEY POS_NM_UNIQUE (POS_NM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='직급 정보 테이블';

--회원 테이블
CREATE TABLE mushroom.org_usr (
  USR_ID INT NOT NULL AUTO_INCREMENT,
  LOGIN_ID VARCHAR(45) NOT NULL,
  USR_NM VARCHAR(45) NOT NULL,
  PWD VARCHAR(200) NOT NULL,
  PWD_DATE CHAR(8) NOT NULL,
  LOCK_YN CHAR(1) DEFAULT 'N',
  STATUS CHAR(1) DEFAULT NULL,

  EMP_NO VARCHAR(20) DEFAULT NULL,
  EMAIL VARCHAR(100) DEFAULT NULL,
  POS_NO INT DEFAULT NULL,
  EXTENSION_NO VARCHAR(10) DEFAULT NULL,       -- 내선번호
  JOB_DESC VARCHAR(200) DEFAULT NULL,           -- 담당업무 설명

  PROFILE_BIO VARCHAR(200) DEFAULT NULL,
  PROFILE_PHOTO BLOB,

  JOIN_DATE CHAR(8) NOT NULL,
  CREATE_DT DATETIME NOT NULL,
  CREATE_ID VARCHAR(45) NOT NULL,
  UPDATE_DT DATETIME NOT NULL,
  UPDATE_ID VARCHAR(45) NOT NULL,

  PRIMARY KEY (USR_ID),
  UNIQUE KEY LOGIN_ID_UNIQUE (LOGIN_ID),
  UNIQUE KEY USR_ID_UNIQUE (USR_ID),
  UNIQUE KEY USR_NM_UNIQUE (USR_NM),
  FOREIGN KEY (POS_NO) REFERENCES mushroom.org_pos(POS_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_090_
